### ISSUE TITLE
injected script breaks browser default XML presentation

### ISSUE THREAD

**Issue by efx** [emberjs/ember-inspector#1136]
As a developer, I use web-browsers to visually inspect XML. Ember inspector injects a script tag that breaks the default browser presentation of the XML.

## Issue and Steps to Reproduce

  - navigate to [https://blog.emberjs.com/feed.xml](https://blog.emberjs.com/feed.xml) in Firefox
  - Observe how the page appears as plaintext instead of formatted XML

I believe this occurs because we indiscriminately append the boot `<script>`:
https://github.com/emberjs/ember-inspector/blob/47138779d4f6c559bda90a0e53df5838ac6da446/skeletons/web-extension/boot.js#L3

### unexpected
<img width="1440" alt="Screen Shot 2020-01-20 at 16 22 06" src="https://user-images.githubusercontent.com/472721/72758514-0782af80-3ba1-11ea-86b2-8a27973a2bfd.png">

### expected
<img width="1440" alt="Screen Shot 2020-01-20 at 16 21 18" src="https://user-images.githubusercontent.com/472721/72758498-fb96ed80-3ba0-11ea-85b9-154df3766968.png">

**Comment by chancancode** [comment]
Hm we should definitely check the document type and inject it conditionally!

**Comment by rwwagner90** [comment]
@chancancode better yet, we should only run inspector when you click the inspector tab.

**Comment by chancancode** [comment]
As things are designed today, this particular script tag has to be injected eagerly to allow the inspector to possibly run later. We can add UI to change which sites to run on, but unless we require a refresh to activate the inspector this isn’t really avoidable at the moment.

**Comment by rwwagner90** [comment]
@chancancode yeah not sure if there is a good solution, but it would be ideal. There have been several reports of this breaking non-Ember sites in some way.

**Comment by efx** [comment]
For this case, I'm entirely happy with inferring the mime type of the page.

**Comment by chancancode** [comment]
@efx that’s probably the fix we can do in the medium term. I don’t know if chrome/firefox let you request that a content script to be injected only on html pages in the manifest. If they do, that’s great. If not, it’s not a big deal, we would just have to detect the document type in the content script and guard the script tag injection accordingly. If you or someone else is able to send a PR, it should be a fairly straightforward fix. Otherwise I’ll do it when I get back from vacation next week.
