### ISSUE TITLE
Route Tab not displaying anything - 3.15

### ISSUE THREAD

**Issue by brandynsparks** [emberjs/ember-inspector#1140]
Hi there,

Ever since I updated from 3.0 to 3.15 my ember inspector will not display anything in the routes tab.  I have tried with a couple other projects and it seems that they work in 3.0 but not 3.15.  Any thoughts on why this could be?
![image](https://user-images.githubusercontent.com/2691253/74175417-6f09a900-4bfb-11ea-98f5-c6359a1d4808.png)

**Comment by rwwagner90** [comment]
@brandynsparks did you solve your issue?

**Comment by brandynsparks** [comment]
@rwwagner90 No I did not.  I still can't get it to work on this one project.  But I think it has to do with something that got messed up while I was cloning the project.  I don't think it is an issue with the "Ember Inspector" but rather my code instead.

**Comment by VasylMarchuk** [comment]
I have been facing this issue forever by the way, and I have always assumed this happens because my projects usually hevily rely on `ember-engines`.

  
<img width="672" alt="Знімок екрана 2020-04-23 о 23 07 33" src="https://user-images.githubusercontent.com/493875/80144567-6b10e480-85b7-11ea-9232-5e38ccab74d0.png">

**Comment by rwwagner90** [comment]
Engines support is definitely lacking. I don't really know how to begin supporting them.
