### ISSUE TITLE
Make arguments in the component tree inspectable

### ISSUE THREAD

**Issue by SYU15** [emberjs/ember-inspector#1169]
Right now only primitives are supported, any objects render as `...`. This will require exploring a few UX options to make sure that it makes sense to the developer/isn't too cumbersome to inspect these arguments vs the entire row.

![Screen_Shot_2020-04-02_at_1 31 08_PM](https://user-images.githubusercontent.com/10149117/78298743-c33c5580-74e7-11ea-8c61-c0e4cbe89862.png)

**Comment by rwwagner90** [comment]
Hi @SYU15! I think @chancancode and I had decided that anything more complex than primitives would require opening the object inspector for the whole row. Perhaps we could still do that, but go one level deeper into the property?

**Comment by chancancode** [comment]
The idea is indeed to open the object inspector. However, opening the object inspector on the component instance isn't necessarily helpful, and in the case of template-only components, there is no component instance to inspect. We chatted on Discord a little, the idea is that when clicking on the `...` it will send that object to the object inspector, similar to what you said.

There are some potentially UX challenges here, as the whole row is currently a clickable area, and adding nested click areas could get uncanny, but @SYU15 will have to prototype it to see how much of an issue it is, in practice. If it turned out to be a problem, one idea would be to stop making the whole row clickable, and instead add a dedicated button to the right (where "scroll into view" and "inspect in elements panel" is currently).

Anyhow, we will still need @SYU15 to prototype the code needed to make inspecting component arguments possible before we can explore the UX problems and solutions.

**Comment by SYU15** [comment]
Yeah @rwwagner90 I will prototype a few different flows and create a WIP PR and we can figure out which one provides the best user experience.

**Comment by nummi** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/3692/78463971-7d72bf00-7698-11ea-898e-68f3cb1fd462.png">

**Comment by chancancode** [comment]
This is done!
