### ISSUE TITLE
Ember inspector does not detect ember application

### ISSUE THREAD

**Issue by kerenhadar** [emberjs/ember-inspector#1828]
I run local ember app, sometimes the ember inspector shows 
"Ember application not detected!" message, most of the time it works fine on he same app.  

ember-cli: 3.20.2
node: 12.21.0
os: win32 x64
Chrome Version 96.0.4664.93 (Official Build) (64-bit)

It started after the 2-days inspector crash about a month ago

**Comment by rwwagner90** [comment]
@kerenhadar are there any messages in the console?

**Comment by ross-kahn** [comment]
I'm also getting this error when running locally. I'm using ember-cli 3.26.1 and chrome 96.0.4664.93 (Official Build) (64-bit). Using Windows 10 Pro x64 19041.1348.

It was working briefly and then stopped as I was making changes to my project. I'm not sure what type of change I was making when it stopped.

**Comment by rwwagner90** [comment]
@ross-kahn I'm looking for any errors or warnings in the console. Try refreshing a few times, closing and opening dev tools etc

**Comment by ross-kahn** [comment]
No errors specifically, but closing and opening dev tools, restarting the server, or refreshing the page sometimes work. It's inconsistent, though.

**Comment by ijestes** [comment]
I am having the same issue. No errors at all

**Comment by kdagnan** [comment]
I am having a similar issue. This occurs on both local development and production code. First time opening DevTools/inspector is fine, but if I reload the page with DevTools open at all (even if not on the Ember tab), then it says no ember app detected. I have to close DevTools and re-open before it will detect the app again. This gets really annoying when developing with live reload - every change I make I have to close DevTools & re-open to debug.

I feel that there's an issue with my setup/system settings because this happens on all of our apps (6 different apps on Ember 3.20 - 3.27), and does not occur for my co-workers with very similar setups. Any ideas on what could be wrong is appreciated! As others have stated, no error messages or any additional information that we can see in console.

I am running MacOS 12.0 with an M1 Pro CPU, with the Universal Chrome Binary installed. I thought the issue was Apple Silicon CPUs but all of my co-workers also got new Apple Silicon macs and are having no issues.

I've tried re-installing both the extension & Chrome.

**Comment by ivansal** [comment]
I have same issue as @kdagnan . In prod and dev env, new and old code first oppening Inspector is fine, but after reload it crashes with message "Ember application not detected!". Clossing and oppening DevTools often helps. Yandex 21.11.3.954 beta

On the same setup in Chome 96.0.4664.110 Inspector work perfectly

**Comment by ross-kahn** [comment]
This has been resolved for me, it will always consistently open when I run locally now.
