### ISSUE TITLE
Models defined using pod syntax are not listed on data tab

### ISSUE THREAD

**Issue by kamalaknn** [emberjs/ember-inspector#202]
While defining models through pod syntax as `app/pods/entity/model.js` in ember-cli, entity is not listed on the data tab.

PS : environment - ember : 1.7.0, ember-data : 1.0.0-beta.8, ember-cli : 0.0.40,

**Comment by teddyzeenny** [comment]
The fix will be in ember-cli's resolver. [This method](https://github.com/emberjs/ember.js/blob/04463cf3f65625fbbdc8b09efaf402a43dca4de0/packages/ember-extension-support/lib/data_adapter.js#L344) does not return the correct value when using pod structures.  We need to return a list of model names `['post', 'comment']` from this method. [This line](https://github.com/ember-cli/ember-resolver/blob/47385252c5dc2bc5c85d34f1a2c3e8ebf1bcf7de/packages/ember-resolver/lib/container-debug-adapter.js#L80) removes `*/models/` from `[prefix]/models/[model-name]` which results in `[model-name]` in a non-pod structure. Pod modules however look like `[prefix]/[model-name]/model.js` if I'm not mistaken. We just need the above line to take both cases into account.

Let's keep this issue here however since it's about the Ember Inspector.

**Comment by teddyzeenny** [comment]
PR submitted https://github.com/ember-cli/ember-resolver/pull/82

**Comment by andrewobrien** [comment]
:+1:
