### ISSUE TITLE
View tree is blank

### ISSUE THREAD

**Issue by ToddSmithSalter** [emberjs/ember-inspector#248]
After the upgrade to 1.6, the view tree no longer shows anything. The Routes panel is working fine, just the current view is non-functional.

![Blank View Tree](https://cloud.githubusercontent.com/assets/157142/4756450/7696bbec-5acd-11e4-8d1e-61f57fc68b07.png)

My app stack:
```
DEBUG: -------------------------------
vendor.js:28474 DEBUG: Ember                       : 1.8.0-beta.5
vendor.js:28474 DEBUG: Ember Data                  : 1.0.0-beta.11
vendor.js:28474 DEBUG: Handlebars                  : 1.3.0
vendor.js:28474 DEBUG: jQuery                      : 1.11.1
vendor.js:28474 DEBUG: Ember Simple Auth           : 0.6.7
vendor.js:28474 DEBUG: Ember Simple Auth OAuth 2.0 : 0.6.7
vendor.js:28474 DEBUG: -------------------------------
```

**Comment by teddyzeenny** [comment]
@marshall-prosperworks ping

**Comment by marshall-prosperworks** [comment]
Sorry, have not had much chance to look into this problem, though we are still experiencing it.

**Comment by teddyzeenny** [comment]
@marshall-prosperworks Is it possible you are deleting the app's `rootElement`? if you search your project for `rootElement` do you get any results?

**Comment by marshall-prosperworks** [comment]
Our project contains a few applications which we run in different contexts. The one that was breaking, was specifying a rootElement of '#application_content', but it seemed that we had no element with that id (running $('#application_content') from the command line got me an empty array).

I saw that we had some other Applications, which were using rootElement: 'body', so i tried changing '#application_content' to 'body', and now the newer inspector version is working. Nice!

Still, it would be nice if the inspector or the framework itself had some better way to deal with this error instead of failing silently. Like, "You specified an applicationRoot which is not present. This will break Ember Inspector and possibly other things"

Anyways, thanks again.

**Comment by marshall-prosperworks** [comment]
Oh I guess i should point out that changing the rootElement to 'body' makes the ember inspector seem to work, but also is messing up my app in other ways, but I guess I just need to figure that out on my end.

**Comment by teddyzeenny** [comment]
If your `rootElement` doesn't exist, you're supposed to get an error from Ember core. See 
http://emberjs.jsbin.com/quxeli/1/edit?html,js,console

**Comment by benedikt-d** [comment]
Having the same issue when there is no root element in the page.

**Comment by locks** [comment]
Closing this for relevancy.
