### ISSUE TITLE
Inspector is stomping app's EmberENV

### ISSUE THREAD

**Issue by ef4** [emberjs/ember-inspector#2500]
This is a non-deterministic failure that depends on how fast the inspector and the app load.

But if the app loads fast and the inspector loads slow, you can suddenly get bizarre results because the inspector completely replaces your `window.EmberENV` with its own [here](https://github.com/emberjs/ember-inspector/blob/ba75238bc4f1e8cdea83d41ebc4761f2e189f66f/skeletons/web-extension/scripts/boot.js#L1). This throws away your own settings.

I think it usually works because the inspector sets first, but that is apparently not guaranteed.

Probably it would be sufficient to make the inspector add properties to an existing `EmberENV` if it finds that one already exists.

**Comment by patricklx** [comment]
Probably need to insert this at the top?
https://github.com/emberjs/ember-inspector/blob/ba75238bc4f1e8cdea83d41ebc4761f2e189f66f/skeletons/web-extension/boot.js#L10

**Comment by patricklx** [comment]
@ef4 do you have an example online website where that happens?
while debugging i found that when boot.js runs, document.documentElement.children is empty. So the page did not yet load.
so even with 
`document.documentElement.appendChild(script)` it will be at the top and run first.

**Comment by patricklx** [comment]
i confirmed it happens here:
https://ember-learn.github.io/ember-cli-addon-docs/

**Comment by nickschot** [comment]
We're likely seeing the same issue. Spotted because suddenly the optional feature `application-template-wrapper` was `true`, causing a visual bug due to the extra html element. Doesn't happen when ember-inspector is disabled.

**Comment by aoumiri** [comment]
Same here, we spend some time debugging this issue thinking it was our code, and that it was impacting our users, but we came to the conclusion that it was ember inspector that was breaking the app.

It happens on chromium browsers: with the ember inspector enabled, we can reproduce the issue, without it the app runs just fine.

Also, I confirm that the issue is random. Sometimes, the plugin's config overwrites the application's one. To reproduce it, you have to try multiple times a page refresh.

We also noticed that it's related to the `application-template-wrapper` param.

**Comment by ef4** [comment]
> Spotted because suddenly the optional feature application-template-wrapper was true, causing a visual bug due to the extra html element. 

Yes, the `application-template-wrapper` setting glitching can also cause `this.element` to be undefined in a rendering test, which was the case I first saw.
