### ISSUE TITLE
How to "fake" the store?

### ISSUE THREAD

**Issue by toranb** [emberjs/ember-inspector#317]
First up - amazing work on this great OSS project! Without this great project a TON of new developers wouldn't/ couldn't grok ember nearly as quickly! thank you, thank you, thank you!

Question: not to introduce a maintenance issue for you or me but I use a project very similar to ember-data (nearly identical api for the raw identity map) but because it's not adapter based it doesn't show up. How trivial would it be for me to "fake" that I'm ember-data just to get quick identity map lookups with the inspector? *(the project is ember-cli based if that helps)*

Again -not trying to impede or put a dependency on this great project in any way. Just looking to see if I could leverage all the great work that's happening here :)

Thanks again for the great OSS work @teddyzeenny and team!

**Comment by teddyzeenny** [comment]
Thanks @toranb, that's really nice to hear :)

The data tab is library agnostic, it should be able to work with any library that uses models and an identity map. You will need to define a data adapter (unrelated to Ember Data adapters) by extending [`Ember.DataAdapter`](https://github.com/emberjs/ember.js/blob/f5873415f2d0e24f8ba731d92bca32d542fd2048/packages/ember-extension-support/lib/data_adapter.js). The [code comments](https://github.com/emberjs/ember.js/blob/f5873415f2d0e24f8ba731d92bca32d542fd2048/packages/ember-extension-support/lib/data_adapter.js#L15-L53) should help you get started.

Since your library is very similar to ED, my advice is to simply copy [ED's data adapter](https://github.com/emberjs/data/blob/d7988679590bff63f4d92c4b5ecab173bd624ebb/packages/ember-data/lib/system/debug/debug_adapter.js) and perform the necessary changes.

You will need to [register the data adapter](https://github.com/emberjs/data/blob/d7988679590bff63f4d92c4b5ecab173bd624ebb/packages/ember-data/lib/initializers/data_adapter.js#L11) as `data-adapter:main` (`app/data-adapter.js` may work in ember-cli). ED also [injects the `store`](https://github.com/emberjs/data/blob/d7988679590bff63f4d92c4b5ecab173bd624ebb/packages/ember-data/lib/initializers/store_injections.js#L12) into the adapter.

Let me know if that works for your case.

**Comment by toranb** [comment]
dude you rawk :) 

thanks for taking the time out of your busy day to reply with such detail !!!
