### ISSUE TITLE
Is there any reason to have an API for extending through 3rd party plugins?

### ISSUE THREAD

**Issue by Zatvobor** [emberjs/ember-inspector#321]
This is a discussion question and might be some kind of feature proposal. 

In context of https://github.com/ember-insights/ember-insights/issues/89 issue we've been thinking about developer's tool as a browser extension that could be based on `ember-inspector` for many reasons.

In short, you are doing a really great tool for Ember development routine which has a lot of reusable things for other tools and frameworks. It makes sense to go with `ember-inspector` with ability to install some kind of extensions manually or this extension could be a part of 3rd party library (let's say `ember-addon`) when the inspector is able to detect and plug it.

Let's start from simple question: Is there any reason to have an API for extending `ember-inspector` through 3rd party plugins? As a result, we're able to contribute this convinience to the `ember-inspector`.

**Comment by teddyzeenny** [comment]
If I understand correctly, you are proposing we allow 3rd party extensions to add features to the inspector? As in the Ember Inspector would have a new tab called "Ember Insights"? Or are you proposing that we extract parts of the Ember Inspector code into an addon so that other extension authors can use it a starting point to build their own devtools tab?

**Comment by Zatvobor** [comment]
> If I understand correctly, you are proposing we allow 3rd party extensions to add features to the inspector?

Exactly. I would like to discuss it in general.

> As in the Ember Inspector would have a new tab called "Ember Insights"?

Right. The main idea behind is to ship `ember-inspector-plugin` with application. Whereas, `ember-inspector` is able to detect certain extension and plug it into the runtime. 

> Or are you proposing that we extract parts of the Ember Inspector code into an addon so that other extension authors can use it a starting point to build their own devtools tab?

Not exactly.

**Comment by teddyzeenny** [comment]
I think this is definitely worth looking into. I'm not sure if it's actually feasible now though, or if it is, to what extent. We should also check if it's compatible with browser extension TOS since almost of them go through a review process; loading code that is not bundled and submitted may be a problem for them.

It is currently possible to somewhat extend the inspector (to a certain extent, definitely not at the level you're proposing). For example, the data tab behavior is [configured and filled](https://github.com/emberjs/ember.js/blob/4bea351dc8db860e590af0a01286dec664c5891a/packages/ember-extension-support/lib/data_adapter.js) by the data library being used by the user. You can also [customize](https://github.com/emberjs/data/blob/58a00dbe6564cd994ef26f01a7bb9bf55f11d119/packages/ember-data/lib/system/debug/debug-info.js) how certain objects are rendered in the object inspector (group properties, show/hide properties). Basically everything related to Ember Data in the inspector is actually extensible because the inspector is not really aware of ED.

So it is currently possible to expand on the existing customization, though this approach has a limit and adding a tab is probably beyond its capabilities. Adding a route probably requires loading code, and may also require [engines](https://github.com/tomdale/rfcs/blob/master/active/0000-engines.md) to be added to Ember.

**Comment by Zatvobor** [comment]
Yeah, I see. BTW, I'll play with it and let you know.
