### ISSUE TITLE
[Glimmer] Cannot read property 'forEach' in ember-debug/view-debug

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember-inspector#351]
I'm seeing the following error when Ember Inspector is installed.  If the inspector is not installed the exception is not thrown.

![](http://i.imgur.com/P30AOOC.png)

```
Ember.Object.extend.appendChildren	@	VM296:2893
Ember.Object.extend.viewTree	@	VM296:2814
(anonymous function)	@	VM296:2775
fn	@	ember.debug.js:377
Queue.invoke	@	ember.debug.js:878
Queue.flush	@	ember.debug.js:943
DeferredActionQueues.flush	@	ember.debug.js:748
Backburner.end	@	ember.debug.js:173
Backburner.run	@	ember.debug.js:228
executeTimers	@	ember.debug.js:610
(anonymous function)	@	ember.debug.js:599

```

**Comment by aceofspades** [comment]
:+1: Halts upgrading for me since I can't browse my view hierarchy at all

**Comment by alexlafroscia** [comment]
I guess that's why it's a canary! ;)

**Comment by teddyzeenny** [comment]
Glimmer removed the concept of virtual views (which is why we were using `_childViews` instead of `childViews`). With virtual views gone, we are no longer able to detect templates that don't have a view class defined (which is a very common case), so replacing `_childViews` with `childViews` will not be enough. I am aware of this issue and currently looking into how this can be resolved.
