### ISSUE TITLE
[1.8.2] `node.chain is not a function` when inspecting model

### ISSUE THREAD

**Issue by poteto** [emberjs/ember-inspector#401]
![node chain](https://cloud.githubusercontent.com/assets/1390709/8233787/1ce1d85e-15a6-11e5-980f-8444b1c1c60f.png)

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.12.1
DEBUG: Ember Data : 1.0.0-beta.18
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

**Comment by poteto** [comment]
The issue is I had a `modelName` computed property macro on my model pointing to `constructor.modelName`. It seems that ember-inspector doesn't like props with that name

**Comment by teddyzeenny** [comment]
Ah that makes sense. This actually may not be an Ember Inspector specific issue. I think it was triggered by the inspector in this case because inspecting an object causes the inspector to observe that object's properties. 

You can probably trigger this error by doing anything that observes the property. For example, try using the property in the template `{{model.modelName}}`. Does that also trigger the error?

A possible solution could be to not have `constructor.modelName` in the CP's dependent keys (which CP macros do automatically). `constructor.modelName` is not an observable property. Instead try using: `modelName: computed(function() { return this.constructor.modelName })`. The value probably won't change during the model's lifetime anyway.
