### ISSUE TITLE
Records of hasMany relationships are exposed as plain text and are not navigable in the inspector

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember-inspector#487]
In the Inspector, I open a record A that has many Bs.

I would like to see a list of related Bs. For that, I click the relationship:

![Imgur](http://i.imgur.com/65RZL8t.png)

and see this:

![Imgur](http://i.imgur.com/c1X2RFL.png)

In order to access the records under the relationship, I click `currentState` and see this:

![Imgur](http://i.imgur.com/SORBeps.png)

The problem is that the records are exposed as plain text, I'm unable to navigate them in the inspector!

**Comment by Patsy-issa** [comment]
If you want to interact with the record (get, set, etc) you can press the `$E` button next to the record to have the inspector output it to the console.

Unless you mean something else by navigate them.

**Comment by lolmaus** [comment]
I mean open that record in the inspector's GUI, not in console.

**Comment by teddyzeenny** [comment]
@lolmaus good point. It seems that maybe ED now stores internal models (instead of actual models) inside the `ManyArray`? Anyway, the reason why you can't click on the models is because they are not Ember objects and to get the actual model you need to call `.getRecord()` on each of them.

My first thought is you can probably do the following:

- Send `answerOccurences` (the `ManyArray`) to the console ($E)
- In the console: `EmberInspector.inspect($E.toArray())`
- Go back to the inspector and click on the model you want in the Object Inspector

This obviously needs to be fixed so it can be easier to navigation `ManyArrays`.

**Comment by jpserrett** [comment]
This is still an issue for me. All relationships show up this way for me. 
![screen shot 2016-02-24 at 8 04 12 am](https://cloud.githubusercontent.com/assets/13526446/13321588/83c7d02c-db95-11e5-9564-a0e4a99c8f43.png)

Also, when I look at the relationship, it defines it as an 'unknown mixin'. 
![screen shot 2016-02-24 at 8 12 24 am](https://cloud.githubusercontent.com/assets/13526446/13321612/a3baa8a0-db95-11e5-9c2c-d15642d1669d.png)

I've had issues being able to use the Ember Inspector since upgrading my Ember app to 2.x. Are these known issues or am I doing something wrong within my code that makes it so that the inspector can't read my data correctly? 

Thanks.

**Comment by teddyzeenny** [comment]
My above comment explains the problem (and a temporary work around). The issue you are describing is definitely a known issue since this is what this open ticket is about - unless you mean other issues that you didn't mention or I don't understand your question?

Even though I would like to get this fixed, it is not technically a bug. Since relationships in ED are no longer stored as Ember objects, and since the Object inspector only inspects Ember objects and arrays, we can no longer use the Object inspector to inspect relationships. It is a regression in the sense that we can no longer do something that we were able to do, however fixing it actually requires adding a new feature (inspecting non-ember objects) rather than fixing a bug.

**Comment by jpserrett** [comment]
Thanks for the response. I was unaware of that specific change to ED, which makes all of this make complete sense now. My main concern was the possibility that we were doing something wrong within our app that caused it to show this way. So good to know its not an issue with our code. 
While a minor inconvenience, at least there is a way to work with the inspector still. 
Thanks again.

**Comment by lolmaus** [comment]
I've started a bounty for this issue: https://freedomsponsors.org/issue/782/records-of-hasmany-relationships-are-exposed-as-plain-text-and-are-not-navigable-in-the-inspector

Please join! $10 so far.

**Comment by rwwagner90** [comment]
@lolmaus is this still an issue and do you have a reproduction? I tried a bit to reproduce, but was unable to.

**Comment by lolmaus** [comment]
Let's close it then. We can reopen if we encounter it again.
