### ISSUE TITLE
Ember inspector does not play nice with chrome dev tools dark theme

### ISSUE THREAD

**Issue by gkaran** [emberjs/ember-inspector#524]
Since Chrome version 29 the option for using a dark theme in developer tools has been added.

When having it enabled and opening ember inspector the following issues appear:
- Theme is not respected (this is not that bad but just mentioning it)
- The attributes panel colouring makes it really hard to read.
- In render performance when no metrics have been acquired the text saying that is hard to read.

![image](https://cloud.githubusercontent.com/assets/1831136/13635591/ce2a91ba-e5ca-11e5-9cdb-b14f8484491f.png)

**Comment by Frozenfire92** [comment]
Now that chrome 50 is launched I feel this issue will affect more people

**Comment by Rio517** [comment]
I wonder what the best way to address this is.  I want to help, but I'm popping in without a ton of knowledge of developing chrome extensions. 

So, the first question is: why?

* My guess is that Ember Inspector is creating a lot of custom elements that prevent it from picking up Dark Theme's CSS styles.  
* It is also possible that the Inspector's styles overwrite default chrome colors. Since these are smart guys, I'm guessing this is not the case.  

Since in the former case, it would actually require a ton of work to make the DOM structure more standardized, the best short term approach might be to have a separate "Dark" version of this Ember inspector.   

A good first step in that direction might be to create a `styles/colors.scss` that would set up current colors as variables, with an eye towards making the existing color palate as consistent as possible (if it isn't already).

Thoughts?  

Perhaps I should open a separate issue to see if such a pull request would be welcome.

**Comment by tonedef** [comment]
Curious if there's any update to this. I love using the dark theme, it's easier on my eyes, it's always a bit of an "aah!" when I switch to the Ember Inspector tab.

**Comment by locks** [comment]
@tonedef are you able to work on the dark theme and figuring out a detection mechanism?

**Comment by ryanponce** [comment]
@stefanpenner Are you saying it would be worth it to create a dark theme specifically for the Ember Inspector as well as a mechanism for toggling between the dark and light themes for the Ember Inspector? Something like a 'Settings' tab or something?

**Comment by rwwagner90** [comment]
This seems to no longer be an issue. The dark theme is still not applied to inspector, but it shows up completely light, without those hard to read elements shown in the original screenshot.

<img width="1191" alt="screen shot 2018-03-06 at 7 44 54 pm" src="https://user-images.githubusercontent.com/2640861/37067270-0910a5d2-2177-11e8-933b-1cb637c0eab9.png">

@locks @teddyzeenny what are your thoughts? I think it is fine to keep inspector always the same theme, personally, unless someone has an easy way to implement it.

**Comment by jedateach** [comment]
@rwwagner90 Agreed. I guess, if anything, this issue could be changed to something like "create dark theme"

**Comment by rwwagner90** [comment]
Closing this in favor of https://github.com/emberjs/ember-inspector/issues/771
