### ISSUE TITLE
Inspector resulting in errors in sandboxed iframes

### ISSUE THREAD

**Issue by justinaray** [emberjs/ember-inspector#560]
I am not sure if this is more a Chrome Extensions issue or could be defeated internally via Programmatic Injection.

The inspector's content-script.js is resulting in console errors because some iframes are sandboxed to not allow javascript.  `Blocked script execution in '...' because .. the 'allow-scripts' permission is not set.`

I recognize that this is just a dev problem, but I am posting it here in case anyone has an easy solution or I should record the bug with Chrome.

**Comment by rwwagner90** [comment]
@justinaray unfortunately, we cannot inject scripts into a sandboxed iframe. We're currently working on a workaround to get inspector to work with ember-twiddle, which uses sandboxed iframes, but it will likely involved manually injected inspector scripts on the iframe side. We will document whatever fix we find, so that developers of sandboxed iframes have a workaround.
