### ISSUE TITLE
Stack trace: TypeError: definedControllerClass.proto is not a function

### ISSUE THREAD

**Issue by p0562153** [emberjs/ember-inspector#629]
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: definedControllerClass.proto is not a function

Ember version => 2.10.0
Ember-cli => 2.10.1
Chrome => 55.0.2883.95
Ember inspector => 2.0.4

Issue to be occurring in chrome. Any idea ?

**Comment by teddyzeenny** [comment]
It's a bit tough to tell. What I know is that `definedControllerClass` is a variable used by Ember core when accessing a controller's class to get its query params. The variable `definedControllerClass` is supposed to contain a controller class. The error here says that `definedControllerClass` doesn't have a `proto` method, and since all Ember Object classes have a `proto` method, my conclusion is that whatever is in `definedControllerClass` is not a controller class. 

Can you check all your controllers and make sure you're exporting `Ember.Controller.extend()`? Make sure you're not exporting `Ember.Controller.create()` or any non-Ember.Object class.

**Comment by p0562153** [comment]
@teddyzeenny 
thank you for your reply. i have checked all controllers and all are extend to Ember.Controller. I downgrade ember cli from 2.10.1 to 2.10.0. then this issue be solved.

**Comment by rwwagner90** [comment]
I have never seen this, and it doesn't seem to occur in latest CLI, so closing for now.
