### ISSUE TITLE
3 errors in tests re: view tree

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember-inspector#648]
<img width="718" alt="screen shot 2017-04-07 at 11 18 47 am" src="https://cloud.githubusercontent.com/assets/8752/24813736/079995d2-1b84-11e7-9e94-309ee21afc33.png">

**Comment by cyril-sf** [comment]
I'm looking at it. 

So far I'd bet for a loose dependency because if I revert to the latest commit that was passing tests, I get the same error.

It seems related to vertical-collection. The proper array is passed to it, but only one element from this array gets rendered.
https://github.com/emberjs/ember-inspector/blob/master/app/templates/view-tree.hbs#L2
