### ISSUE TITLE
Convert Firefox add-on to use the Chrome WebExtension

### ISSUE THREAD

**Issue by clarkbw** [emberjs/ember-inspector#666]
Here's a tracking issue to pull in all the related pieces needed to make the current WebExtension work within Firefox.  Firefox 57 (coming in November) will be removing support for the add-on SDK and should have full support for all the WebExtension APIs used here.

- [x] `chrome.extension.onConnect` used [here](https://github.com/emberjs/ember-inspector/blob/master/skeletons/chrome/background-script.js#L75), needs to be updated to use [runtime.onConnect](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onConnect)
- [x] `chrome.extension.onMessage` used [here](https://github.com/emberjs/ember-inspector/blob/master/skeletons/chrome/background-script.js#L109) needs to be updated to use [runtime.onMessage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage)
- [x] `chrome.extension.sendMessage` used a lot in [content-script.js](https://github.com/emberjs/ember-inspector/blob/master/skeletons/chrome/content-script.js#L43) needs to be updated to use [runtime.sendMessage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage)

I'll look through the rest of the errors and keep updating this list as I go.

**Comment by clarkbw** [comment]
Here's where the progress is so far: https://github.com/emberjs/ember-inspector/compare/master...clarkbw:firefox-webextension

I'm actually now running into an issue that seems present on Chrome as well as Firefox and prevents the panel from running at all.

**Comment by clarkbw** [comment]
Just ran into this odd bug when making this change f19eab946f3e68c5c25afa7694af72b5c8da62bc where the icon color is inverted when not selected.  I believe its [bug 1366755](https://bugzilla.mozilla.org/show_bug.cgi?id=1366755) and hopefully it will get fixed soon.

Before | After | Bug when not selected
--------- | --------- | ----------
<img width="161" alt="screen shot 2017-06-01 at 3 57 05 pm" src="https://cloud.githubusercontent.com/assets/2134/26698266/45e9c44e-46e3-11e7-9e04-bd43bc32625b.png"> | <img width="145" alt="screen shot 2017-06-01 at 3 57 47 pm" src="https://cloud.githubusercontent.com/assets/2134/26698261/437e5b34-46e3-11e7-9cf3-ba8f4f1693f7.png"> | <img width="133" alt="screen shot 2017-06-01 at 4 00 37 pm" src="https://cloud.githubusercontent.com/assets/2134/26698309/793cd480-46e3-11e7-9acd-3628b6c06509.png">

**Comment by locks** [comment]
@clarkbw thank you for the help, it's very appreciated! Anything on the Ember side blocking you?

**Comment by clarkbw** [comment]
Thanks @locks! I'm seeing an error when running the WebExtension in both chrome and Firefox. Is there an issue tracking something? I'll check my install again, it feels like I have a newer version of some npm / bower package that is breaking things.

**Comment by clarkbw** [comment]
This is the error I'm seeing in the the extension (Chrome & Firefox): https://stackoverflow.com/questions/44003015/ember-js-typeerror-ember2-default-string-is-undefined-ember-s

**Comment by clarkbw** [comment]
Here's what the error looks like in the Chrome console: (this is coming from master and not just my branch)

```
index.js:25 Uncaught TypeError: Cannot read property 'camelize' of undefined
    at chrome-extension://aahkfefopgdpmocdinghnfdebnmoncdh/panes-2-7-0/assets/vendor.js:90386:51
    at Array.forEach (native)
    at exports.default (chrome-extension://aahkfefopgdpmocdinghnfdebnmoncdh/panes-2-7-0/assets/vendor.js:90378:8)
    at Module.callback (chrome-extension://aahkfefopgdpmocdinghnfdebnmoncdh/panes-2-7-0/assets/ember-inspector.js:527:41)
    at Module.exports (chrome-extension://aahkfefopgdpmocdinghnfdebnmoncdh/panes-2-7-0/assets/vendor.js:124:32)
    at requireModule (chrome-extension://aahkfefopgdpmocdinghnfdebnmoncdh/panes-2-7-0/assets/vendor.js:39:18)
    at chrome-extension://aahkfefopgdpmocdinghnfdebnmoncdh/panes-2-7-0/assets/ember-inspector.js:16034:3
(anonymous) @ index.js:25
exports.default @ index.js:17
(anonymous) @ app.js:67
Module.exports @ loader.js:114
requireModule @ loader.js:29
(anonymous) @ app-boot.js:2
```

**Comment by clarkbw** [comment]
> believe its bug 1366755 and hopefully it will get fixed soon.

The fix for this just landed and ship with Firefox 55

**Comment by clarkbw** [comment]
Tried this again but I'm hitting the same error in Chrome and Firefox just in the master branch of this repo, not my own changes.

Here's another stack overflow issue I found that's similar to the error I'm seeing. 
https://stackoverflow.com/questions/44475787/emberjs-ember-load-initializers-error-after-newer-npm-install

@locks if you have any idea what's happening here or how I can fix it I'd appreciate it.

**Comment by teddyzeenny** [comment]
@clarkbw I'm on it!

**Comment by mikl** [comment]
Firefox 57 beta 1 dropped yesterday, so I wanted to try building this version to see how it works.

Not an expert when it comes to web extensions, but here is what I found:

<details>
  <summary>Click to view my findings, screenshots and all</summary>

If you load the extension as a temporary extension via the browser UI, the browser complains:

> Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

<img width="834" alt="screen shot 2017-09-20 at 22 31 27" src="https://user-images.githubusercontent.com/10263/30666114-97334eac-9e53-11e7-8688-089f70e62dae.png">

Loaded this way, the plugin only loads in new tabs opened thereafter. Confused by this, I went a level deeper, loading it via Mozilla’s CLI script, by running `npx web-ext run --firefox=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin` from the `dist/chrome` folder. This starts a “clean” Firefox with the extention loaded, and automatically reloads on changes. Nifty, but it does not appear to change the outcome, but it does make it easier to debug, since any other extensions you might have installed in your regular profile won’t disturb.

So, once properly rigged for debugging, I loaded a local Ember 2.15 app, that works fine with the inspector otherwise, and watched the fireworks. Here’s what I found:

1. The Ember [DEV] tab does show up in the developer tools. Due to errors in loading the Ember app inside, it remains blank.
2. Once the plugin is loaded, the console for the the Ember app I was trying to debug shows a bunch of errors that appears to be spilling out of the extension somehow – these errors do not appear without the plugin loaded: <img width="1284" alt="screen shot 2017-09-20 at 22 48 27" src="https://user-images.githubusercontent.com/10263/30666956-393f6530-9e56-11e7-9438-7731b27d022a.png">
3. When viewing the console of the extension itself, the same errors appear, plus even more severe errors: <img width="1163" alt="screen shot 2017-09-20 at 22 52 02" src="https://user-images.githubusercontent.com/10263/30667015-6e787c32-9e56-11e7-8ada-4d9006d25cbb.png">

I did compile the extension using Node 8.5.0, ignoring the compatibility protestations from the older version of ember-cli that the inspector currently uses. This might explain some of the issues.
</details>

I hope this is somewhat helpful. If anyone can point me in the right direction on where to look for solutions, I’ll be happy to dig further.

**Comment by locks** [comment]
@mikl thank you so much for taking the time to take detailed notes, screenshots and all!

**Comment by teddyzeenny** [comment]
@mikl there was a pending [PR](https://github.com/emberjs/ember-inspector/pull/715) that was merged today to support Firefox WebExtensions. Do you mind checking if `dist/firefox` on latest master solves the issues you reported?

**Comment by mikl** [comment]
@teddyzeenny yes, with the latest master, on FF 57 beta 1, the plugin now loads and seems to work as expected.

However, the console is still full of warnings and errors, so something is not quite right:

<details>
  <summary>Click to view screenshots of error console</summary>

Just the errors:

<img width="1169" alt="screen shot 2017-09-22 at 15 21 23" src="https://user-images.githubusercontent.com/10263/30746572-773b9e80-9faa-11e7-9e58-a92421911ef1.png">

Errors and warnings:

<img width="1169" alt="screen shot 2017-09-22 at 15 21 38" src="https://user-images.githubusercontent.com/10263/30746579-7aee0072-9faa-11e7-89d7-b1dfef0d7e0a.png">

</details>

**Comment by mattmarcum** [comment]
Cool - I was able to build and run the extension using this guide: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox

Is there a way to build and install a local copy permanently?

**Comment by andreicristianpetcu** [comment]
Zip-it then upload it [here](https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted). You will get an unlisted but signed extension. If you upload it to a github repo as a release then you can install it with one click. [Here is an example](https://github.com/andreicristianpetcu/google_translate_this/releases/download/v1.2.7/google_translate_this_page-1.2.7-an.fx.xpi)

**Comment by jsmestad** [comment]
For folks who come across this issue via Google (like I did). Here is how to get master into FF Quantum - http://blog.overstuffedgorilla.com/ember-inspector-working-on-firefox-developer-edition/

**Comment by teddyzeenny** [comment]
The inspector is now published as a WebExtension so you should be able to install it.

**Comment by clarkbw** [comment]
I'm seeing it here! https://addons.mozilla.org/en-US/firefox/addon/ember-inspector/

🎉  🎈

**Comment by rmmmp** [comment]
@clarkbw, weird when I visit that link it still shows 2.0.6 for me and that's what's being installed in browser.

**Comment by teddyzeenny** [comment]
@rmmmp a reviewer unfortunately disabled the addon on Firefox due to having `unsafe-eval` in the [manifest file](https://github.com/emberjs/ember-inspector/blob/06acfc74e4228f5b99adbd7e650e70381f2d4ff5/skeletons/web-extension/manifest.json#L17).
