### ISSUE TITLE
[feature discussion] ability to configure value for "Hide Empty Model Types"

### ISSUE THREAD

**Issue by efx** [emberjs/ember-inspector#741]
# use case
As a developer in a large app, we use a number of different ember data models. Often when developing one section, I only care about seeing one's loaded in the store. Thus I would like to be able to save a preference to toggle this on.
I would see this as simple checkbox navigated to from Ember Inspector's options link:
<img width="543" alt="screen shot 2017-12-20 at 1 50 27 pm" src="https://user-images.githubusercontent.com/472721/34223293-cf3fca5c-e58c-11e7-91dd-888cd3036ed1.png">

# prior work
https://github.com/emberjs/ember-inspector/pull/458/files

**Comment by teddyzeenny** [comment]
That sounds reasonable. What do you think about remembering your last choice instead of making it a configuration? On a related note, I think a search feature would be really useful for large apps as well.

**Comment by efx** [comment]
ah, yeah that is more sensible. Basically persisting it via the addon's install state. (localStorage under the hood I imagine?)
Yes, search would be great.

**Comment by teddyzeenny** [comment]
Are you interested in submitting a PR?
It would consist of making [this property](https://github.com/emberjs/ember-inspector/blob/1c34df9e8e7f521b380d09d6f7d3af15c650cc78/app/controllers/model-types.js#L11) a CP instead of an options property.

Something like:
```js
  hideEmptyModels: computed({
    get() {
      return !!this.get('storage').getItem('are-model-types-hidden');
    },
    set(key, value) {
      this.get('storage').setItem('are-model-types-hidden', value);
      return value;
    }
  })
```

[Here's a similar approach](https://github.com/emberjs/ember-inspector/blob/40aa0238ccf2b075f067ad5f34915dc63591ce29/app/controllers/render-tree.js#L17-L45).

**Comment by efx** [comment]
@teddyzeenny definitely. I can try to put something together over the next few weeks. I like how simple your snippet is; will make implementing a breeze.
