### ISSUE TITLE
Ember Inspector has errored with ember-feature-flags

### ISSUE THREAD

**Issue by vladucu** [emberjs/ember-inspector#814]
Hi,

Not sure if this is the right place, but thought of reporting this

Ember Inspector: `3.1.1`
Ember: `3.1.2`
Ember CLI: `3.1.4`
Ember Feature Flags: `5.0.0`

In our app, we inject the `features` service in routes, components, etc using an initializer. Trying to click on any component, route, etc triggers the following in console and fails to open the Inspector tab
<img width="957" alt="screen shot 2018-05-31 at 2 12 00 pm" src="https://user-images.githubusercontent.com/160955/40779235-d297ebb0-64dc-11e8-940d-004653ac96b2.png">

**NOTE:**

- if we remove the initializer and inject the `features` service manually the tab works when clicking on components/routes... but still in Ember Inspector clicking on Container in the sidebar then on the features service same thing still happens

**Comment by rwwagner90** [comment]
@vladucu without doing further debugging, I would blindly guess this is an issue with: https://github.com/emberjs/ember-inspector/blob/e6015b1cd18f339820120532a5b3a014e3ef16fe/ember_debug/object-inspector.js#L476

Would you be interested in potentially trying to determine if that is where the issue is and if so adding a fix there? If that is where the issue lies, potentially we could do a check for if the object is a proxy somehow, and use `.get('type')` otherwise just grab `.type`?

**Comment by vladucu** [comment]
@rwwagner90 sure, will try to confirm if this is the cause and maybe a fix...thx for pointing me in the right direction
