### ISSUE TITLE
Problems with ember-cli-deprecation-workflow

### ISSUE THREAD

**Issue by gandalfar** [emberjs/ember-inspector#857]
When trying to use ember-cli-deprecation-workflow with current version of ember-inspector in Chrome 69 beta:  (3.3.1), I'm trying to run: `deprecationWorkflow.flushDeprecations()`

but I always get an empty list of deprecations:
```
"window.deprecationWorkflow = window.deprecationWorkflow || {};
window.deprecationWorkflow.config = {
  workflow: [

  ]
};"
```

If I disable ember-inspector, I get correct list of deprecations (in this case):
```
window.deprecationWorkflow = window.deprecationWorkflow || {};
window.deprecationWorkflow.config = {
  workflow: [
    { handler: "silence", matchId: "ember-routing.route-router" }
  ]
};
```

I would also assume that using deprecation-workflow, would prevent ember-inspector from showing `Deprecations were detected, see the Ember Inspector deprecations tab for more details.` and notifying me about silenced deprecations.

All versions from Info:

Ember Inspector | 3.3.1
Ember | 3.2.2
Ember Data | 3.3.1
jQuery | 3.3.1
Ember Django Adapter | 2.0.0
Ember Simple Auth | 1.7.0
Frontend | 1.0.0+a1f1bb93

**Comment by rwjblue** [comment]
This interaction isn’t something we’ve thought of before. We fixed the way we hook into deprecations in https://github.com/emberjs/ember-inspector/pull/845, but since we are now _never_ bubbling deprecations up (e.g. we don’t call `next‘) things like ember-cli-deprecation-workflow’s `flushDeprecations` does not work (since it just never saw any deprecations).

At the very least we should properly document this issue (and maybe detect it for you) over in ember-cli-deprecation-workflow...

**Comment by rwwagner90** [comment]
@rwjblue should we just add the `next()` call perhaps or add in a way to let them come through for this use case? Maybe even just add a button to call `flushDeprecations` from the deprecations tab of inspector?

**Comment by rwwagner90** [comment]
@rwjblue let me know which you think is better. We could also do a hybrid where we call `next` to allow them through, but then have a setting to either show them in the console or not.

**Comment by robustdj** [comment]
I'll give this one a shot
