### ISSUE TITLE
accessing currentPath from application controller has been deprecated

### ISSUE THREAD

**Issue by gokatz** [emberjs/ember-inspector#973]
We tried to access `currentPath` [here](https://github.com/emberjs/ember-inspector/blob/master/ember_debug/route-debug.js#L49) and these such access has been [deprecated in 3.10](https://deprecations.emberjs.com/v3.x/#toc_application-controller-router-properties). Can we use the [router implementation](https://github.com/emberjs/ember-inspector/blob/master/ember_debug/route-debug.js#L20) instead ?

**Comment by rwwagner90** [comment]
@gokatz this is in ember_debug code, which needs to support back to Ember 2.7. We may need a conditional that checks the Ember version and uses different logic based on the version. If you wanted to try switching to the other implementation, it is possible it might work. I am away until June 3rd, and won't have a ton of time to look into this until then.

cc @rwjblue @pzuraq

**Comment by rwjblue** [comment]
Ya, the router service only works from 2.15+. 

I think the simplest fix is to update:

https://github.com/emberjs/ember-inspector/blob/65409c9ab2084899fb4eb48e222fb6e1f77c048b/ember_debug/route-debug.js#L29

To use `namespace.owner.router.currentPath` instead. It has been around since 2.1 ([added in this commit](https://github.com/emberjs/ember.js/commit/f3ab6c283e462f401f0a083beb677c434a5cde31)).

**Comment by gokatz** [comment]
That's super fast. Thanks @rwwagner90 and @rwjblue 🍾

**Comment by rwwagner90** [comment]
@gokatz we aim to please 😄

**Comment by rwwagner90** [comment]
Is everything working well for you now?

**Comment by gokatz** [comment]
Yeah. Works perfectly.
